package cli

import (
	"bytes"
	_ "embed"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

//go:embed SKILL.md
var skillMD []byte

// generatedMarker identifies a SKILL.md that rmine wrote. install refuses to
// overwrite a file without it: `rmine` is a plausible name for a skill someone
// wrote by hand, and silently replacing their work is not a reasonable
// side effect of installing a CLI.
const generatedMarker = "<!-- generated by rmine"

var skillCmd = &cobra.Command{
	Use:   "skill",
	Short: "Manage the rmine Claude Code skill",
}

var skillInstallCmd = &cobra.Command{
	Use:   "install",
	Short: "Install rmine's reference as a Claude Code skill",
	RunE: func(cmd *cobra.Command, args []string) error {
		local, _ := cmd.Flags().GetBool("local")
		force, _ := cmd.Flags().GetBool("force")

		dir, err := skillDir(local)
		if err != nil {
			return err
		}
		path, err := installSkill(dir, force)
		if err != nil {
			return err
		}
		return printAction(fmt.Sprintf("Installed Claude Code skill to %s", path), actionResult{Status: "installed", Path: path})
	},
}

var skillUninstallCmd = &cobra.Command{
	Use:   "uninstall",
	Short: "Remove the installed rmine Claude Code skill",
	RunE: func(cmd *cobra.Command, args []string) error {
		local, _ := cmd.Flags().GetBool("local")
		force, _ := cmd.Flags().GetBool("force")

		dir, err := skillDir(local)
		if err != nil {
			return err
		}
		path := filepath.Join(dir, "SKILL.md")

		existing, err := os.ReadFile(path)
		if os.IsNotExist(err) {
			return printAction(fmt.Sprintf("No rmine skill installed at %s", path), actionResult{Status: "absent", Path: path})
		}
		if err != nil {
			return fmt.Errorf("reading skill file: %w", err)
		}
		if !force && !bytes.Contains(existing, []byte(generatedMarker)) {
			return fmt.Errorf("%s was not written by rmine; pass --force to remove it anyway", path)
		}

		if err := os.Remove(path); err != nil {
			return fmt.Errorf("removing skill file: %w", err)
		}
		// Only succeeds when nothing else lives there, which is what we want.
		_ = os.Remove(dir)

		return printAction(fmt.Sprintf("Removed Claude Code skill at %s", path), actionResult{Status: "uninstalled", Path: path})
	},
}

func init() {
	for _, c := range []*cobra.Command{skillInstallCmd, skillUninstallCmd} {
		c.Flags().Bool("local", false, "act on this project's .claude/skills instead of the user-level one")
		c.Flags().Bool("force", false, "proceed even if the file was not written by rmine")
	}
	skillCmd.AddCommand(skillInstallCmd, skillUninstallCmd)
	rootCmd.AddCommand(skillCmd)
}

// skillDir returns where the skill lives: Claude Code's user-level directory
// by default, or the current project's when --local is given, for a skill
// that should travel with the repository rather than the machine.
func skillDir(local bool) (string, error) {
	if local {
		wd, err := os.Getwd()
		if err != nil {
			return "", fmt.Errorf("resolving working directory: %w", err)
		}
		return filepath.Join(wd, ".claude", "skills", "rmine"), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolving home directory: %w", err)
	}
	return filepath.Join(home, ".claude", "skills", "rmine"), nil
}

// stampedSkill returns the embedded SKILL.md with a provenance line inserted
// after its front matter. The file tells the reader to regenerate it after
// upgrading rmine, which is only actionable if the file says which rmine
// wrote it.
func stampedSkill() []byte {
	stamp := fmt.Sprintf("\n%s %s; regenerate with `rmine skill install` -->\n", generatedMarker, Version())

	const fence = "---\n"
	if bytes.HasPrefix(skillMD, []byte(fence)) {
		if end := bytes.Index(skillMD[len(fence):], []byte(fence)); end >= 0 {
			cut := len(fence) + end + len(fence)
			out := make([]byte, 0, len(skillMD)+len(stamp))
			out = append(out, skillMD[:cut]...)
			out = append(out, stamp...)
			return append(out, skillMD[cut:]...)
		}
	}
	return append([]byte(stamp), skillMD...)
}

// installSkill writes the stamped SKILL.md into dir. A file rmine generated
// is overwritten without ceremony — it holds no state worth preserving — but
// one it did not write is left alone unless force says otherwise.
func installSkill(dir string, force bool) (string, error) {
	path := filepath.Join(dir, "SKILL.md")

	existing, err := os.ReadFile(path)
	switch {
	case err == nil:
		if !force && !bytes.Contains(existing, []byte(generatedMarker)) {
			return "", fmt.Errorf("%s already exists and was not written by rmine; pass --force to overwrite it", path)
		}
	case !os.IsNotExist(err):
		return "", fmt.Errorf("reading existing skill file: %w", err)
	}

	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("creating skill directory: %w", err)
	}
	if err := os.WriteFile(path, stampedSkill(), 0o644); err != nil {
		return "", fmt.Errorf("writing skill file: %w", err)
	}
	return path, nil
}

// promptInstallSkill asks (default yes) whether to install the Claude Code
// skill, once, at the end of `config init`.
func promptInstallSkill() error {
	if !confirm("Install the rmine Claude Code skill (teaches AI assistants how to drive rmine)?", true) {
		return nil
	}

	dir, err := skillDir(false)
	if err != nil {
		return err
	}
	path, err := installSkill(dir, false)
	if err != nil {
		// The profile is already saved and usable; a skill that could not be
		// written is worth reporting but not worth failing setup over.
		promptf("Skipped installing the Claude Code skill: %v\n", err)
		return nil
	}
	return printAction(fmt.Sprintf("Installed Claude Code skill to %s", path), actionResult{Status: "installed", Path: path})
}
