package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// withSkillFile runs as an rmine of the given version, with a user-level
// SKILL.md holding content.
func withSkillFile(t *testing.T, running, content string) string {
	t.Helper()
	prev := version
	version = running
	t.Cleanup(func() { version = prev })

	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Chdir(t.TempDir())
	dir, _ := skillDir(false)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(dir, "SKILL.md")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}

func stampedBy(v string) string {
	return "---\nname: rmine\n---\n\n" + generatedMarker + " " + v + "; regenerate with `rmine skill install` -->\n\nbody\n"
}

func TestWarnsWhenTheSkillWasGeneratedByAnotherVersion(t *testing.T) {
	path := withSkillFile(t, "v0.8.0", stampedBy("v0.5.1"))

	_, stderr, err := runCLIErr(t, "version")
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{path, "v0.5.1", "v0.8.0", "`rmine skill install`"} {
		if !strings.Contains(stderr, want) {
			t.Errorf("warning should mention %q, got %q", want, stderr)
		}
	}
}

func TestNoWarningWhenTheSkillMatches(t *testing.T) {
	withSkillFile(t, "v0.8.0", stampedBy("v0.8.0"))

	if _, stderr, _ := runCLIErr(t, "version"); stderr != "" {
		t.Errorf("expected no warning, got %q", stderr)
	}
}

func TestWarnsAboutASkillFromBeforeTheMarker(t *testing.T) {
	withSkillFile(t, "v0.8.0", "# Reference\n\nGenerated by `rmine skill install` — don't hand-edit.\n")

	if _, stderr, _ := runCLIErr(t, "version"); !strings.Contains(stderr, "an older rmine") {
		t.Errorf("expected a warning about an older rmine, got %q", stderr)
	}
}

func TestNoWarningForAHandWrittenSkill(t *testing.T) {
	withSkillFile(t, "v0.8.0", "---\nname: rmine\n---\n\nMy own notes.\n")

	if _, stderr, _ := runCLIErr(t, "version"); stderr != "" {
		t.Errorf("expected no warning, got %q", stderr)
	}
}

func TestNoWarningFromADevelopmentBuild(t *testing.T) {
	for _, running := range []string{"dev", "v0.7.1+dirty"} {
		withSkillFile(t, running, stampedBy("v0.5.1"))

		if _, stderr, _ := runCLIErr(t, "version"); stderr != "" {
			t.Errorf("%s: expected no warning, got %q", running, stderr)
		}
	}
}

func TestSkillInstallDoesNotWarnAboutTheFileItReplaces(t *testing.T) {
	withSkillFile(t, "v0.8.0", stampedBy("v0.5.1"))

	_, stderr, err := runCLIErr(t, "skill", "install")
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(stderr, "generated by") {
		t.Errorf("install warned about the file it was replacing: %q", stderr)
	}
	if _, stderr, _ := runCLIErr(t, "version"); stderr != "" {
		t.Errorf("expected no warning after reinstalling, got %q", stderr)
	}
}

func TestWarningForAProjectSkillSuggestsLocal(t *testing.T) {
	withSkillFile(t, "v0.8.0", stampedBy("v0.8.0"))
	dir, _ := skillDir(true)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "SKILL.md"), []byte(stampedBy("v0.6.0")), 0o644); err != nil {
		t.Fatal(err)
	}

	_, stderr, _ := runCLIErr(t, "version")
	if !strings.Contains(stderr, "`rmine skill install --local`") || strings.Count(stderr, "generated by") != 1 {
		t.Errorf("expected one warning suggesting --local, got %q", stderr)
	}
}
